language: csharp
solution: ./travis-test.sln
mono:
  - latest
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - nuget restore ./travis-test.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:PostBuildEventUseInBuild=false /p:PreBuildEvent="" /p:PostBuildEvent="" /p:TargetFrameworkProfile="" ./travis-test.sln
  - cd ./travis-test/bin/Release/
  - mono --runtime=v4.0 ../../../testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe travis-test.dll
